package adapters

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/joebhakim/themer/internal/config"
)

type recordingRunner struct {
	name   string
	args   []string
	result CommandResult
	err    error
}

func (r *recordingRunner) Run(_ context.Context, name string, args ...string) (CommandResult, error) {
	r.name = name
	r.args = append([]string(nil), args...)
	return r.result, r.err
}

func TestFishApplySessionRefreshWritesRefreshScript(t *testing.T) {
	dir := t.TempDir()
	refreshPath := filepath.Join(dir, "theme.fish")
	configHome := filepath.Join(dir, "config")
	t.Setenv("XDG_CONFIG_HOME", configHome)
	legacyPath := filepath.Join(configHome, "fish", "conf.d", "fish_frozen_theme.fish")
	if err := os.MkdirAll(filepath.Dir(legacyPath), 0o755); err != nil {
		t.Fatalf("mkdir legacy dir: %v", err)
	}
	if err := os.WriteFile(legacyPath, []byte("# old"), 0o644); err != nil {
		t.Fatalf("write legacy file: %v", err)
	}

	runner := &recordingRunner{
		result: CommandResult{
			Stdout: "fish_color_command 88c0d0 --theme=nord\nfish_color_normal normal --theme=nord\n",
		},
	}
	adapter := NewFish(config.FishConfig{
		ApplyMode:   config.FishApplyModeSessionRefresh,
		RefreshPath: refreshPath,
	}, runner)

	if err := adapter.Apply(context.Background(), "nord"); err != nil {
		t.Fatalf("apply theme: %v", err)
	}
	if runner.name != "fish" {
		t.Fatalf("runner name = %q, want fish", runner.name)
	}
	if len(runner.args) < 2 {
		t.Fatalf("runner args = %#v", runner.args)
	}
	script := runner.args[1]
	if !strings.Contains(script, "fish_config theme choose \"nord\"") || !strings.Contains(script, "fish_config theme dump") {
		t.Fatalf("fish refresh script generation command is missing choose/dump:\n%s", script)
	}
	if strings.Contains(script, "mkdir -p") {
		t.Fatalf("fish refresh mode should not write startup globals:\n%s", script)
	}

	data, err := os.ReadFile(refreshPath)
	if err != nil {
		t.Fatalf("read refresh script: %v", err)
	}
	written := string(data)
	if !strings.Contains(written, "themer fish-refresh | source") {
		t.Fatalf("refresh script missing usage hint:\n%s", written)
	}
	if !strings.Contains(written, `set --global fish_color_command "88c0d0" "--theme=nord"`) {
		t.Fatalf("refresh script missing command color:\n%s", written)
	}
	if _, err := os.Stat(legacyPath); !os.IsNotExist(err) {
		t.Fatalf("legacy startup file still exists: %v", err)
	}
}

func TestFishApplyUniversalPersistsUniversalVars(t *testing.T) {
	runner := &recordingRunner{}
	adapter := NewFish(config.FishConfig{
		ApplyMode: config.FishApplyModeUniversal,
	}, runner)

	if err := adapter.Apply(context.Background(), "nord"); err != nil {
		t.Fatalf("apply theme: %v", err)
	}
	if runner.name != "fish" {
		t.Fatalf("runner name = %q, want fish", runner.name)
	}
	if len(runner.args) < 2 {
		t.Fatalf("runner args = %#v", runner.args)
	}
	script := runner.args[1]
	if !strings.Contains(script, "set --universal $color $$color") {
		t.Fatalf("universal apply script missing universal writes:\n%s", script)
	}
	if !strings.Contains(script, "set --universal themer_current_theme \"nord\"") {
		t.Fatalf("universal apply script missing theme marker:\n%s", script)
	}
	if strings.Contains(script, "fish_config theme dump") || strings.Contains(script, "mkdir -p") {
		t.Fatalf("unexpected legacy/session-refresh logic in universal mode:\n%s", script)
	}
}

func TestFishCurrentUsesRefreshScriptThemeMarker(t *testing.T) {
	dir := t.TempDir()
	refreshPath := filepath.Join(dir, "theme.fish")
	data := []byte("# Generated by themer.\n# themer fish theme: github-dark\nset --global fish_color_command \"ffffff\"\n")
	if err := os.WriteFile(refreshPath, data, 0o644); err != nil {
		t.Fatalf("write refresh script: %v", err)
	}
	adapter := NewFish(config.FishConfig{
		ApplyMode:   config.FishApplyModeSessionRefresh,
		RefreshPath: refreshPath,
	}, &recordingRunner{})

	current, err := adapter.Current(context.Background())
	if err != nil {
		t.Fatalf("current theme: %v", err)
	}
	if current != "github-dark" {
		t.Fatalf("current = %q, want github-dark", current)
	}
}

func TestFishRefreshScriptClearsSessionOverridesInUniversalMode(t *testing.T) {
	adapter := NewFish(config.FishConfig{
		ApplyMode: config.FishApplyModeUniversal,
	}, &recordingRunner{})

	script, err := adapter.RefreshScript()
	if err != nil {
		t.Fatalf("refresh script: %v", err)
	}
	if !strings.Contains(script, "set --erase --global $color") {
		t.Fatalf("universal refresh script missing global erase:\n%s", script)
	}
	if !strings.Contains(script, "commandline -f repaint") {
		t.Fatalf("universal refresh script missing repaint:\n%s", script)
	}
}

func TestFishDescribeIncludesModeSpecificGuidanceAndSamplePreview(t *testing.T) {
	runner := &recordingRunner{
		result: CommandResult{
			Stdout: "+-- sample --+\n| command |\n+------------+\n",
		},
	}
	adapter := NewFish(config.FishConfig{
		ApplyMode:   config.FishApplyModeSessionRefresh,
		RefreshPath: "/tmp/themer-fish-refresh.fish",
	}, runner)

	description, err := adapter.Describe(context.Background(), "nord")
	if err != nil {
		t.Fatalf("describe theme: %v", err)
	}
	if runner.name != "fish" {
		t.Fatalf("runner name = %q, want fish", runner.name)
	}
	if len(runner.args) < 2 {
		t.Fatalf("runner args = %#v", runner.args)
	}
	if !strings.Contains(runner.args[1], "fish_config theme choose \"nord\"") {
		t.Fatalf("describe script does not choose theme:\n%s", runner.args[1])
	}
	if len(description.Samples) != 3 {
		t.Fatalf("samples = %#v, want 3 lines", description.Samples)
	}
	if description.Samples[1] != "| command |" {
		t.Fatalf("sample line = %q, want %q", description.Samples[1], "| command |")
	}
	if len(description.Notes) == 0 || !strings.Contains(strings.Join(description.Notes, "\n"), "fish-refresh | source") {
		t.Fatalf("describe notes missing session refresh guidance: %#v", description.Notes)
	}
}
